# Generated by Django 2.1.3 on 2018-11-11 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='price',
        ),
    ]
