# Generated by Django 2.1.3 on 2018-11-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_questioncomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='downvote_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='upvote_count',
            field=models.IntegerField(default=0),
        ),
    ]
