# Generated by Django 2.1.3 on 2018-11-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20181121_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='total_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questioncomment',
            name='total_count',
            field=models.IntegerField(default=0),
        ),
    ]
