# Generated by Django 2.1.3 on 2018-11-23 12:08

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20181122_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description',
            field=froala_editor.fields.FroalaField(),
        ),
        migrations.AlterField(
            model_name='questioncomment',
            name='comment_description',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
