# Generated by Django 2.1.3 on 2018-11-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='downvote_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answers',
            name='upvote_count',
            field=models.IntegerField(default=0),
        ),
    ]
